apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 767397692469.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:702a0cba2759061e69f246ce312818b84fb36126
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: electronics-service
  labels:
    app: electronics
spec:
  type: ClusterIP
  selector:
    app: electronics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
