apiVersion: apps/v1
kind: Deployment
metadata:
  name: appliances-deployment
  labels:
    app: appliances
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appliances
  template:
    metadata:
      labels:
        app: appliances
    spec:
      containers:
      - name: appliances
        image: 891376978717.dkr.ecr.us-east-1.amazonaws.com/shopping-site-appliances:016048d7af4970669b23af29bbe9f033cd0ec32b
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: appliances-service
  labels:
    app: appliances
spec:
  type: ClusterIP
  selector:
    app: appliances
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
